### ISSUE TITLE
Query - Does the /workday API support a comma separated list of countries?

### ISSUE THREAD

**Issue by recipher** [holidayapi/holidayapi-node#37]
In the developer docs, it states that /holidays supports up to 10 countries in a comma-separated list.

Does the /workday API also support multiple countries? If not, can it?

Thanks.

**Comment by joshtronic** [comment]
Hey @recipher 

Currently only our /v1/holidays endpoint supports multiple countries. Hasn't actually come up for our other endpoints so it hasn't been something we've considered at all.

Since /v1/workday doesn't return an array of data currently, we'd have to redo the payload for the endpoint, which wouldn't happen until we version from v1 to v2 of the API (which is probably a ways off).

I'm curious about what the use case would be for needing to calculate the next business day for a bulk of countries at one time. Feel free to drop us a line at hello@holidayapi.com
